"""Shared public/runtime limits for SHARD operations."""

MAX_TOP_K = 50
MAX_SEMANTIC_TARGETS = 20
MAX_EMBEDDING_TIMEOUT_SECONDS = 86_400
MAX_EMBEDDING_POLL_SECONDS = 60.0
MAX_TEMPERATURE = 2.0
MAX_NEW_TOKENS = 16_384

